#!/system/bin/sh
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 
echo "conservative" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
chmod 666 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 
echo "1080000" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 

